-- Add subject column to contacts table
ALTER TABLE public.contacts
ADD COLUMN subject TEXT;

-- Update RLS policies to include subject column
ALTER POLICY "Public users can create contact messages" ON contacts
USING (true)
WITH CHECK (true);

-- If the contacts table doesn't exist, create it
CREATE TABLE IF NOT EXISTS public.contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT,
  message TEXT NOT NULL,
  responded BOOLEAN DEFAULT FALSE
);

-- Add subject column if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'contacts' 
        AND column_name = 'subject'
    ) THEN
        ALTER TABLE public.contacts ADD COLUMN subject TEXT;
    END IF;
END
$$;

-- Set up RLS for contacts table if it doesn't exist
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

-- Create or replace policies for the contacts table
DO $$
BEGIN
    -- Drop policies if they exist (to avoid errors)
    DROP POLICY IF EXISTS "Public users can create contact messages" ON public.contacts;
    DROP POLICY IF EXISTS "Admins can read contact messages" ON public.contacts;
    DROP POLICY IF EXISTS "Admins can update contact messages" ON public.contacts;
    
    -- Create new policies
    CREATE POLICY "Public users can create contact messages" ON public.contacts FOR INSERT WITH CHECK (true);
    CREATE POLICY "Admins can read contact messages" ON public.contacts FOR SELECT TO authenticated USING (is_admin());
    CREATE POLICY "Admins can update contact messages" ON public.contacts FOR UPDATE TO authenticated USING (is_admin());
END
$$; 